spring:
  security:
    user:
      name: root
      password: 123456
  threads:
    virtual:
      enabled: true
  flyway:
    # 起始版本
    baseline-version: 0
    # 历史记录
    baseline-on-migrate: true
    # 避免数据被意外清空
    clean-disabled: false
  application:
    name: iot-flyway-postgresql
  datasource:
    dynamic:
      p6spy: false
      strict: false
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/test?tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=flyway-postgresql&useSSL=false&reWriteBatchedInserts=true
          username: root
          password: laokou123
          hikari:
            min-idle: 200
            minimum-idle: 200
            maximum-pool-size: 500
            max-pool-size: 500
            connection-timeout: 600000
            idle-timeout: 600000
            validation-timeout: 600000
            initialization-fail-timeout: 600000
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test?tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=flyway-postgresql&useSSL=false&reWriteBatchedInserts=true
          username: root
          password: laokou123
