spring:
  application:
    name: dynamic-datasource-micrometer
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/master
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
